# -*- coding: utf-8 -*-
"""YOLO_food_detection_health_app_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vk_cvg1mJ-U5xZ7tQw--CB60pF79Xga

# Food Detection + Calorie & Health-Suitability Assistant
### (Elderly health-check app — Pakistan)
"""

from google.colab import drive
drive.mount('/content/drive')

import os

BASE_DIR = '/content/drive/MyDrive/FoodHealthApp'
DATASET_DIR = os.path.join(BASE_DIR, 'dataset')
WEIGHTS_DIR = os.path.join(BASE_DIR, 'weights')
RESULTS_DIR = os.path.join(BASE_DIR, 'results')
EXPORT_DIR = os.path.join(BASE_DIR, 'exports')
NUTRITION_DIR = os.path.join(BASE_DIR, 'nutrition')
CHARTS_DIR = os.path.join(BASE_DIR, 'charts')

for d in [BASE_DIR, DATASET_DIR, WEIGHTS_DIR, RESULTS_DIR, EXPORT_DIR, NUTRITION_DIR, CHARTS_DIR]:
    os.makedirs(d, exist_ok=True)

print('Project folders ready under:', BASE_DIR)

!pip install -q ultralytics roboflow pandas matplotlib seaborn requests

from getpass import getpass
from roboflow import Roboflow
import yaml

api_key = getpass('enter api key: ')
rf = Roboflow(api_key=api_key)

DATASETS_TO_DOWNLOAD = [

    {
        'name': 'my_original_food_dataset',
        'workspace': 'project-4lmm2',
        'project': 'foods-qshht',
        'version': 7
    },


    {
        'name': 'indian_food_detection',
        'workspace': 'project-z0tql',
        'project': 'indian-food-detection-kzw9g',
        'version': 1
    },
    {
        'name': 'indian_food_image_dataset',
        'workspace': 'edi-8pxxa',
        'project': 'indian-food-image-lieir',
        'version': 1
    },


    {
        'name': 'fast_food_ufdjx',
        'workspace': 'ntsuu',
        'project': 'fast-food-ufdjx',
        'version': 19
    },
    {
        'name': 'multi_object_food',
        'workspace': 'workeveryday',
        'project': 'multi-object-food-detection',
        'version': 1
    },
    {
        'name': 'fast_food_classification',
        'workspace': 'abdul-ikram-nz2nx',
        'project': 'fast-food-classification-ddqyc',
        'version': 1
    },


    {
        'name': 'vegetables_kacga',
        'workspace': 'test-on9hk',
        'project': 'vegetables-kacga',
        'version': 1
    },
    {
        'name': 'fruits_and_vegetables',
        'workspace': 'datasets-wqqwv',
        'project': 'fruits-and-vegetables-un1ow',
        'version': 2
    },
    {
        'name': 'ingredient_detection',
        'workspace': 'object-detection-yolo-v8',
        'project': 'ingredient-detection-yolo',
        'version': 1
    }
]


downloaded_datasets = {}
all_classes = {}

for entry in DATASETS_TO_DOWNLOAD:
    print(f"\nDownloading '{entry['name']}' ({entry['workspace']}/{entry['project']} v{entry['version']}) ...")
    try:
        project = rf.workspace(entry['workspace']).project(entry['project'])
        version = project.version(entry['version'])
        dest = os.path.join(DATASET_DIR, entry['name'])
        dataset = version.download('yolov8', location=dest)
        downloaded_datasets[entry['name']] = dataset

        with open(os.path.join(dataset.location, 'data.yaml')) as f:
            classes = yaml.safe_load(f).get('names', [])
        all_classes[entry['name']] = classes
        print(f"  -> {len(classes)} classes: {classes}")
    except Exception as e:
        print(f"  !! Skipped '{entry['name']}': {e}")
        print('     Double check the workspace/project/version match the dataset\'s Roboflow page exactly.')

master_classes = sorted({cls for classes in all_classes.values() for cls in classes})

print(f'{len(master_classes)} unique classes across {len(all_classes)} dataset(s):\n')
for c in master_classes:
    print(' -', c)

with open(os.path.join(DATASET_DIR, 'master_class_list.txt'), 'w') as f:
    f.write('\n'.join(master_classes))
print('\nSaved to', os.path.join(DATASET_DIR, 'master_class_list.txt'))

from ultralytics import YOLO

# Point this at whichever dataset (or merged dataset) you're training on.
TRAIN_DATA_YAML = os.path.join(downloaded_datasets['my_original_food_dataset'].location, 'data.yaml')

# yolov8s.pt = small, fast, good starting point for mobile deployment.
model = YOLO('yolov8s.pt')

results = model.train(
    data=TRAIN_DATA_YAML,
    epochs=50,
    imgsz=640,
    project=WEIGHTS_DIR,
    name='food_detector',
    exist_ok=True,
)

best_weights = os.path.join(WEIGHTS_DIR, 'food_detector', 'weights', 'best.pt')
trained_model = YOLO(best_weights)

metrics = trained_model.val(data=TRAIN_DATA_YAML)
print(metrics)

from IPython.display import Image, display

run_dir = os.path.join(WEIGHTS_DIR, 'food_detector')
display(Image(filename=os.path.join(run_dir, 'confusion_matrix.png')))
display(Image(filename=os.path.join(run_dir, 'results.png'), width=700))

import requests
import time
import pandas as pd

usda_api_key = getpass('Enter your (free) USDA FoodData Central API key: ')

def query_usda_nutrition(food_name, api_key, timeout=10):
    """Looks up one food name in USDA FoodData Central and returns a dict of
    the nutrients we care about, or None if nothing usable was found."""
    url = 'https://api.nal.usda.gov/fdc/v1/foods/search'
    params = {'query': food_name, 'pageSize': 1, 'api_key': api_key}
    try:
        resp = requests.get(url, params=params, timeout=timeout)
        resp.raise_for_status()
        results = resp.json().get('foods', [])
    except Exception as e:
        print(f'  lookup failed for {food_name}: {e}')
        return None

    if not results:
        return None

    nutrients = {n['nutrientName']: n['value'] for n in results[0].get('foodNutrients', [])}

    def get(*names, default=0):
        for n in names:
            if n in nutrients:
                return nutrients[n]
        return default

    return {
        'class_name': food_name,
        'serving_description': '100g (USDA reference amount)',
        'calories': get('Energy'),
        'carbs_g': get('Carbohydrate, by difference'),
        'sugar_g': get('Sugars, total including NLEA', 'Sugars, total'),
        'fat_g': get('Total lipid (fat)'),
        'cholesterol_mg': get('Cholesterol'),
        'sodium_mg': get('Sodium, Na'),
        'source': 'USDA (auto)',
    }

rows = []
not_found = []

for food_name in master_classes:
    result = query_usda_nutrition(food_name, usda_api_key)
    if result:
        rows.append(result)
        print(f'  found: {food_name}')
    else:
        not_found.append(food_name)
        print(f'  NOT FOUND (needs manual entry): {food_name}')
    time.sleep(0.2)  # be polite to the free API

auto_nutrition_df = pd.DataFrame(rows) if rows else pd.DataFrame(columns=['class_name'])

print(f'\n{len(rows)} classes auto-filled, {len(not_found)} need manual entry.')
if not_found:
    print('Manual entry needed for:', not_found)

manual_nutrition_rows = [
    # Fill these in / add more rows for whatever showed up in 'not_found' above.
    # VERIFY every value before using with real users.
    {'class_name': 'biryani', 'serving_description': '1 cup (~250g)', 'calories': 350, 'carbs_g': 45, 'sugar_g': 3,  'fat_g': 12, 'cholesterol_mg': 45,  'sodium_mg': 600, 'source': 'manual - VERIFY'},
    {'class_name': 'daal',    'serving_description': '1 cup (~200g)', 'calories': 200, 'carbs_g': 30, 'sugar_g': 2,  'fat_g': 5,  'cholesterol_mg': 0,   'sodium_mg': 400, 'source': 'manual - VERIFY'},
    {'class_name': 'roti',    'serving_description': '1 piece (~40g)', 'calories': 120, 'carbs_g': 22, 'sugar_g': 1,  'fat_g': 2,  'cholesterol_mg': 0,   'sodium_mg': 150, 'source': 'manual - VERIFY'},
    {'class_name': 'karahi',  'serving_description': '1 serving (~250g)', 'calories': 400, 'carbs_g': 10, 'sugar_g': 3, 'fat_g': 28, 'cholesterol_mg': 90,  'sodium_mg': 700, 'source': 'manual - VERIFY'},
    {'class_name': 'nihari',  'serving_description': '1 bowl (~300g)', 'calories': 450, 'carbs_g': 15, 'sugar_g': 2, 'fat_g': 30, 'cholesterol_mg': 100, 'sodium_mg': 800, 'source': 'manual - VERIFY'},
]

manual_nutrition_df = pd.DataFrame(manual_nutrition_rows)

nutrition_csv_path = os.path.join(NUTRITION_DIR, 'nutrition_table.csv')

# Manual entries take priority over auto-filled ones for the same class name.
combined = pd.concat([auto_nutrition_df, manual_nutrition_df], ignore_index=True)
nutrition_df = combined.drop_duplicates(subset='class_name', keep='last').reset_index(drop=True)

nutrition_df.to_csv(nutrition_csv_path, index=False)
print(f'Saved {len(nutrition_df)} rows to {nutrition_csv_path}')
nutrition_df

CONDITION_LIMITS = {
    'diabetes':          {'sugar_g': 10, 'carbs_g': 30},
    'high_cholesterol':  {'cholesterol_mg': 60, 'fat_g': 15},
    'hypertension':      {'sodium_mg': 400},
}

def check_food_suitability(food_name, user_conditions, nutrition_df=nutrition_df):
    row = nutrition_df[nutrition_df['class_name'].str.lower() == food_name.lower()]
    if row.empty:
        return f"{food_name}: no nutrition data yet."

    row = row.iloc[0]
    warnings = []
    for condition in user_conditions:
        for nutrient, limit in CONDITION_LIMITS.get(condition, {}).items():
            value = row.get(nutrient, 0)
            if pd.notna(value) and value > limit:
                warnings.append(f"{nutrient.replace('_', ' ')} is {value} (above the {limit} guideline for {condition})")

    if warnings:
        return f"{food_name.title()} ({row['calories']} kcal per {row['serving_description']}): CAUTION — " + '; '.join(warnings) + '.'
    return f"{food_name.title()} ({row['calories']} kcal per {row['serving_description']}): looks fine in a normal portion."

print(check_food_suitability('nihari', ['diabetes', 'high_cholesterol']))

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style='whitegrid', font_scale=1.0)

# A single steady hue for magnitude comparisons (calories) — dark = higher.
plot_df = nutrition_df.dropna(subset=['calories']).sort_values('calories', ascending=True)

fig, ax = plt.subplots(figsize=(8, max(3, 0.4 * len(plot_df))))
colors = sns.light_palette('#2E6F9E', n_colors=len(plot_df))
bars = ax.barh(plot_df['class_name'].str.title(), plot_df['calories'], color=colors)
for bar, val in zip(bars, plot_df['calories']):
    ax.text(bar.get_width() + 2, bar.get_y() + bar.get_height() / 2, f'{val:.0f}', va='center', fontsize=9)
ax.set_xlabel('Calories (kcal)')
ax.set_title('Calories by detected food')
ax.spines[['top', 'right']].set_visible(False)
plt.tight_layout()
plt.savefig(os.path.join(CHARTS_DIR, 'calories_by_food.png'), dpi=150)
plt.show()

# Small multiples for the other nutrients — one axis each, so scales never mix.
nutrients_to_plot = [
    ('carbs_g', 'Carbs (g)'),
    ('fat_g', 'Fat (g)'),
    ('sugar_g', 'Sugar (g)'),
    ('sodium_mg', 'Sodium (mg)'),
]

fig, axes = plt.subplots(2, 2, figsize=(11, 8))
palette = ['#2E6F9E', '#3E8E7E', '#B0793B', '#8C5A9E']  # fixed categorical order, one color per subplot

for ax, (col, label), color in zip(axes.flat, nutrients_to_plot, palette):
    d = nutrition_df.dropna(subset=[col]).sort_values(col, ascending=True)
    ax.barh(d['class_name'].str.title(), d[col], color=color)
    ax.set_title(label)
    ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.savefig(os.path.join(CHARTS_DIR, 'macros_small_multiples.png'), dpi=150)
plt.show()

TEST_IMAGE = os.path.join(DATASET_DIR, 'test_plate.jpg')

def analyze_plate(image_path, user_conditions, model=trained_model, nutrition_df=nutrition_df, conf=0.4):
    results = model.predict(source=image_path, conf=conf, save=False, verbose=False)
    detected = sorted({model.names[int(box.cls)] for r in results for box in r.boxes})

    if not detected:
        print('No food detected — try a clearer or closer photo.')
        return

    print(f'Detected: {", ".join(detected)}\n')
    for food in detected:
        print('-', check_food_suitability(food, user_conditions, nutrition_df))

    subset = nutrition_df[nutrition_df['class_name'].str.lower().isin([d.lower() for d in detected])]
    if not subset.empty:
        fig, ax = plt.subplots(figsize=(6, 3))
        ax.bar(subset['class_name'].str.title(), subset['calories'], color='#2E6F9E')
        ax.set_ylabel('Calories (kcal)')
        ax.set_title('This plate')
        ax.spines[['top', 'right']].set_visible(False)
        plt.tight_layout()
        plt.show()

analyze_plate(TEST_IMAGE, user_conditions=['diabetes', 'hypertension'])

"""## Sources

- [Indian Food Detection — Roboflow Universe](https://universe.roboflow.com/project-z0tql/indian-food-detection-kzw9g)
- [Indian Food YOLOv5 — Roboflow Universe](https://universe.roboflow.com/smart-india-hackathon/indian-food-yolov5)
- [Pakistani-Food-Recognizer — GitHub](https://github.com/ahsantahseen/Pakistani-Food-Recognizer)
- [Fast Food Finder — Roboflow Universe](https://universe.roboflow.com/algebra/fast-food-finder)
- [Fast Food Dataset — Roboflow Universe](https://universe.roboflow.com/fast-food-dataset/fast-food-dataset-zpies)
- [Fruits and Vegetables — Roboflow Universe](https://universe.roboflow.com/datasets-wqqwv/fruits-and-vegetables-un1ow)
- [Fruits and Vegetable Detection — Roboflow Universe](https://universe.roboflow.com/e3/fruits-and-vegetable-detection-y0n90)
- [Food-101 Dataset — Roboflow Universe](https://universe.roboflow.com/gec-bilaspur/food-101-dataset)
- [USDA FoodData Central API](https://fdc.nal.usda.gov/api-key-signup)

"""